import './js/support.js';
import './js/switcher.js';
import './js/render-category-list.js';
import './js/catalog.js';
import './js/localStorageApi.js';
import './js/pop-up/renderModal.js';
import './js/pop-up/openModal.js';
import './js/pop-up/getDataBooksById.js';
// import './js/modal.js';
import './js/modal-avtorization.js';
import './js/scroll-up.js';
import './js/pop-up/addBookStorage.js';
import './js/mobile-menu.js';
import './js/mobile-menu-log-out.js';
import './js/loader.js';
import './js/authorization.js';
