import './js/support.js';
import './js/switcher.js';
import './js/localStorageApi.js';
import './js/shopping-list-card';
import './js/render-shopping-list';
import './js/pop-up/getDataBooksById';
// import './js/modal.js';
import './js/modal-avtorization.js';
import './js/mobile-menu.js';
import './js/mobile-menu-log-out.js';
import './js/pagination.js';
import './js/authorization.js';
